### ISSUE TITLE
Develop validation logic for create new memo

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/simple-memo-react#10]
# Goal

Make validation logic and implement the logic to creating new memo function

# To-Do

- [x] Validate the memo's content is empty when click create button
- [x] If pass the validation, keep going and make new memo
- [x] If fail to the validation, show the error message and do not make new memo
