### ISSUE TITLE
Reduce duplicate code

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/simple-memo-react#11]
# Goal

Make the duplicate codes to a function and recycle the code

# To-Do

- [x] Separate function for finding memo object in memo list
- [x] Separate function for finding memo index in memo list
- [x] Separate function for check if the object's id is same with the given id
- [x] Make function for return negative value of the given value
