### ISSUE TITLE
Refactor business logic functions

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/simple-memo-react#12]
# Goal

Make unit functions for make state changes and make business logic functions by composing them

# To-Do

- [x] Make 'setNewMemo' function
- [x] Implement 'setNewMemo' function
- [x] Make 'unshiftMemos' function
- [x] Implement 'unshiftMemos' function
- [x] Make 'filterMemos' function
- [x] Implement 'filterMemos' function
- [x] Make 'replaceMemos' function
- [x] Implement 'replaceMemos' function
