### ISSUE TITLE
Validate when save editing memo

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/simple-memo-react#13]
# Goal

Validate empty memo when user save editing memo

# To-Do

- [x] Make 'validateMemo' function
- [x] Implement to 'validateCreateNewMemo' function
- [x] Make 'validateEditingMemo' function using 'validateMemo' function
- [x] Validate memo when save editing memo
  - If pass validation
    - Keep going and save editing memo
  - If failed to pass validation
    - [x] Show error message
    - [x] Reset editing memo content
