### ISSUE TITLE
Implement library

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/simple-memo-react#16]
# Goal

- Implement library to the project

# To-Do

- [x] Install underscore.js
- [x] Implement underscore.js to functions
- [x] Make custom methods
  - [x] Make _.pipe
  - [x] Make _.go
