### ISSUE TITLE
Implement atomic design

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/simple-memo-react#8]
# Goal

Using atomic design pattern, structure the project

# To-Do

- [x] Make 'atom' folder
  - [x] Make 'Button' component ( button/index.js )
  - [x] Separate button area to 'Button' component
  - [x] Make 'InputText' component ( input_text/index.js )
  - [x] Separate input area to 'InputText' component
- [x] Make 'molecule' folder
  - [x] Make 'MemoCard' component ( memo_card/index.js )
  - [x] Separate memo card area to 'MemoCard' component
- [x] Make 'organism' folder
  - [x] Make 'MemoPageHeader' component ( memo_page_header/index.js )
  - [x] Separate header area of the app to 'MemoPageHeader' component
  - [x] Make 'MemoPageMain' component ( memo_page_main/index.js )
  - [x] Separate main area of the app to 'MemoPageMain' component
- [x] Make 'page' folder
  - [x] Make 'MemoPage' component ( memo_page/index.js, memo_page/presenter.js )
  - [x] Move business logic code to 'MemoPage' component ( index.js )
  - [x] Move JSX to 'MemoPage' component ( presenter.js )
- [x] Implement 'MemoPage' component to 'App' component
  - 'App' component handle only router and page changes ( currently no such functionality )
